# Site Settings
title: "Dr. Farshid Pirahansiah"
email: mylastname@gmail.com  
description: "Expertise in Computer Vision, ML, LLM"
baseurl: "" 
url: "https://www.pirahansiah.com"
twitter_username: pirahansiah
github_username: pirahansiah

name: "pirahansiah"
author: "Dr. Farshid Pirahansiah"
markdown: kramdown
permalink: /:title/

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  linkify: true

include:
  - farshid

plugins:
  - jekyll-feed
  - jekyll-seo-tag
navigation:
  - title: "Home"
    url: "/"
  - title: "Farshid"
    children:
      - title: "Products"
        url: "/farshid/portfolio/projects/Solutions"  
      - title: "Resources"
        url: "/farshid/Resources"  
      - title: "Social"
        url: "/farshid/Social"      
      - title: "Portfolio"
        children:
          - title: "Publications"
            url: "/farshid/portfolio/publications/"
            children:
                - title: "CV_Patents"
                  url: "/farshid/portfolio/publications/CV/"
